"""deduplicate active links by original URL

Revision ID: 7351e688a2ac
Revises: 3e67c45c2282
Create Date: 2026-08-15 21:36:51.217726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7351e688a2ac'
down_revision: Union[str, Sequence[str], None] = '3e67c45c2282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_original_url', 'links', ['original_url'], unique=True, postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_original_url', table_name='links', postgresql_where=sa.text('is_active IS true'))
    # ### end Alembic commands ###
